/**
 * Static content pages.
 *
 * All four policy pages now carry HUEGLAM's own published text, supplied by
 * the store owner. Two things still need the owner's attention before launch
 * and are marked needsReview:
 *   - The privacy policy and terms both name Shopify as the host/processor,
 *     which stops being true once this site goes live.
 *   - The refund policy contains both a 30-day return clause (Shopify's
 *     template) and a 2-day clause (HUEGLAM's own), which contradict.
 */

export type StaticPage = {
  slug: string;
  title: string;
  updated: string;
  needsReview: boolean;
  body: string[];
};

const RETURNS_AND_REFUND: string[] = [
  "<h3>Returns and Refund</h3>",
  "<p>Thank you for shopping at The HUEGLAM. We have made all our products with utmost care and deep scientific knowledge with an understanding of most skin types. If you are still not completely satisfied with a purchase, please reach out to us and we will put all our efforts to help you. Kindly make an unboxing video for easy reference.</p>",
  "<p>We offer refund / replacement only in the following cases:</p>",
  "<ol>",
  "<li>Wrong product delivered</li>",
  "<li>Expired product delivered</li>",
  "<li>Damaged product delivered &ndash; Physical damage</li>",
  "<li>Missing product</li>",
  "</ol>",
  '<p>Step 1 &ndash; Raise a request within 2 days from the date of delivery along with an unboxing video through Email &ndash; <a href="mailto:support@hueglam.com">support@hueglam.com</a> or on WhatsApp at <a href="tel:+918886677330">+918886677330</a> with the pictures of the issue you are facing and your order ID.</p>',
  "<p>Step 2 &ndash; Allow us 48 working hours to review your request.</p>",
  "<p>Step 3 &ndash; On reviewing your request, we will send our courier partner to collect the product delivered to you.</p>",
  "<p>Step 4 &ndash; After your product(s) is received, we will verify it and initiate the replacement or refund accordingly.</p>",
  "<h3>Under what conditions return / replacement requests will not be accepted?</h3>",
  "<ul>",
  "<li>Opened/used/altered products.</li>",
  "<li>Original packaging (mono cartons, labels, etc.) missing.</li>",
  "<li>The return/replacement request is generated after 2 days from the date of delivery.</li>",
  "<li>The damaged/ missing product is reported after 2 days from the date of delivery.</li>",
  "<li>Update received as product delivered but product not received and if reported after 24 hours from the time of delivery.</li>",
  "</ul>",
];

const SHIPPING_SECTION: string[] = [
  "<h3>Where do we ship to?</h3>",
  "<p>We ship to almost every city in India. We do not offer an international shipping option currently, but we hope to offer it in the future.</p>",
  "<h3>How long does an order take to process?</h3>",
  "<p>We try to process the orders within 24 working hours, in most cases we try to fulfil the order within 5 working days, but please allow us 7 working days to fulfil the order. Order delivery time may vary during peak periods (after/during product launches, holidays and special promotions).</p>",
  "<h3>How long does it take to ship?</h3>",
  "<p>We ship all confirmed orders within 24 working hours. You will receive an email once your order is shipped with your tracking number. We work as hard as we can to try to meet your expectations, but sometimes there may be delays &ndash; e.g. because of postal/carrier delays, logistics, bad weather, or things out of our control.</p>",
  "<h3>How can you track your order?</h3>",
  "<p>Once your order has been dispatched from our warehouse, you will receive an email with your tracking information.</p>",
  "<h3>Cancellations</h3>",
  '<p>You can cancel your orders by writing to us on our Email ID &ndash; <a href="mailto:support@hueglam.com">support@hueglam.com</a> or please call us at <a href="tel:8886677330">8886677330</a> (Monday to Friday, 10AM to 7PM &amp; Saturday 10AM to 4PM) and we will help you cancel the order.</p>',
  "<h3>How will I receive the refund for my cancelled order?</h3>",
  "<p>For prepaid orders, money will be returned to the bank account/credit/debit card or where the payment was made within 7 business working days. We will be able to credit to the original method of payment, we cannot refund to another alternative card.</p>",
  "<p><strong>Please Note:</strong> Orders can only be cancelled before they are shipped.</p>",
];

export const staticPages: StaticPage[] = [
  {
    slug: "contact",
    title: "Contact us",
    updated: "2026-09-28",
    needsReview: false,
    body: [
      "<p>We read every message and usually reply within one business day.</p>",
      "<h3>Email</h3>",
      '<p><a href="mailto:support@hueglam.com">support@hueglam.com</a></p>',
      "<h3>Phone</h3>",
      '<p><a href="tel:8886677330">8886677330</a> &middot; Monday to Friday, 10AM to 7PM &middot; Saturday, 10AM to 4PM</p>',
      "<h3>WhatsApp</h3>",
      '<p><a href="tel:+918886677330">+91 8886677330</a></p>',
      "<h3>Instagram</h3>",
      '<p><a href="https://www.instagram.com/hueglam_official" target="_blank" rel="noreferrer noopener">@hueglam_official</a></p>',
      "<h3>Registered office</h3>",
      "<p>Nyoraa Consumers Pvt Ltd<br>Plot B/5, Flat 201, MSR Complex, Adithya Nagar<br>Hyderabad 500085</p>",
    ],
  },
  {
    slug: "shipping-policy",
    title: "Shipping policy",
    updated: "2026-09-28",
    needsReview: false,
    body: ["<h3>Shipping &amp; Returns</h3>", ...SHIPPING_SECTION, ...RETURNS_AND_REFUND],
  },
  {
    slug: "refund-policy",
    title: "Refund policy",
    updated: "2026-09-28",
    needsReview: true,
    body: [
      "<h3>Shipping &amp; Returns</h3>",
      "<p>We have a 30-day return policy, which means you have 30 days after receiving your item to request a return.</p>",
      "<p>To be eligible for a return, your item must be in the same condition that you received it, unworn or unused, with tags, and in its original packaging. You&rsquo;ll also need the receipt or proof of purchase.</p>",
      '<p>To start a return, you can contact us at <a href="mailto:support@hueglam.com">Support@hueglam.com</a>. Please note that returns will need to be sent to the following address: [INSERT RETURN ADDRESS]</p>',
      "<p>If your return is accepted, we&rsquo;ll send you a return shipping label, as well as instructions on how and where to send your package. Items sent back to us without first requesting a return will not be accepted.</p>",
      '<p>You can always contact us for any return question at <a href="mailto:support@hueglam.com">Support@hueglam.com</a>.</p>',
      "<h3>Damages and issues</h3>",
      "<p>Please inspect your order upon reception and contact us immediately if the item is defective, damaged or if you receive the wrong item, so that we can evaluate the issue and make it right.</p>",
      "<h3>Exceptions / non-returnable items</h3>",
      "<p>Certain types of items cannot be returned, like perishable goods (such as food, flowers, or plants), custom products (such as special orders or personalized items), and personal care goods (such as beauty products). We also do not accept returns for hazardous materials, flammable liquids, or gases. Please get in touch if you have questions or concerns about your specific item.</p>",
      "<p>Unfortunately, we cannot accept returns on sale items or gift cards.</p>",
      "<h3>Exchanges</h3>",
      "<p>The fastest way to ensure you get what you want is to return the item you have, and once the return is accepted, make a separate purchase for the new item.</p>",
      "<h3>European Union 14 day cooling off period</h3>",
      "<p>Notwithstanding the above, if the merchandise is being shipped into the European Union, you have the right to cancel or return your order within 14 days, for any reason and without a justification. As above, your item must be in the same condition that you received it, unworn or unused, with tags, and in its original packaging. You&rsquo;ll also need the receipt or proof of purchase.</p>",
      "<h3>Refunds</h3>",
      "<p>We will notify you once we&rsquo;ve received and inspected your return, and let you know if the refund was approved or not. If approved, you&rsquo;ll be automatically refunded on your original payment method within 10 business days. Please remember it can take some time for your bank or credit card company to process and post the refund too.</p>",
      '<p>If more than 15 business days have passed since we&rsquo;ve approved your return, please contact us at <a href="mailto:support@hueglam.com">Support@hueglam.com</a>.</p>',
      ...SHIPPING_SECTION,
      ...RETURNS_AND_REFUND,
    ],
  },
  {
    slug: "privacy-policy",
    title: "Privacy policy",
    updated: "2025-02-03",
    needsReview: true,
    body: [
      '<p>This Privacy Policy describes how HUEGLAM (the "Site", "we", "us", or "our") collects, uses, and discloses your personal information when you visit, use our services, or make a purchase from hueglam.com (the "Site") or otherwise communicate with us regarding the Site (collectively, the "Services"). For purposes of this Privacy Policy, "you" and "your" means you as the user of the Services, whether you are a customer, website visitor, or another individual whose information we have collected pursuant to this Privacy Policy.</p>',
      "<p>Please read this Privacy Policy carefully. By using and accessing any of the Services, you agree to the collection, use, and disclosure of your information as described in this Privacy Policy. If you do not agree to this Privacy Policy, please do not use or access any of the Services.</p>",
      "<h3>Changes to This Privacy Policy</h3>",
      '<p>We may update this Privacy Policy from time to time, including to reflect changes to our practices or for other operational, legal, or regulatory reasons. We will post the revised Privacy Policy on the Site, update the "Last updated" date and take any other steps required by applicable law.</p>',
      "<h3>How We Collect and Use Your Personal Information</h3>",
      "<p>To provide the Services, we collect personal information about you from a variety of sources, as set out below. The information that we collect and use varies depending on how you interact with us.</p>",
      "<p>In addition to the specific uses set out below, we may use information we collect about you to communicate with you, provide or improve the Services, comply with any applicable legal obligations, enforce any applicable terms of service, and to protect or defend the Services, our rights, and the rights of our users or others.</p>",
      "<h3>What Personal Information We Collect</h3>",
      '<p>The types of personal information we obtain about you depends on how you interact with our Site and use our Services. When we use the term "personal information", we are referring to information that identifies, relates to, describes or can be associated with you.</p>',
      "<h3>Information We Collect Directly from You</h3>",
      "<ul>",
      "<li>Contact details including your name, address, phone number, and email.</li>",
      "<li>Order information including your name, billing address, shipping address, payment confirmation, email address, and phone number.</li>",
      "<li>Account information including your username, password, security questions and other information used for account security purposes.</li>",
      "<li>Customer support information including the information you choose to include in communications with us.</li>",
      "</ul>",
      "<p>Some features of the Services may require you to directly provide us with certain information about yourself. You may elect not to provide this information, but doing so may prevent you from using or accessing these features.</p>",
      "<h3>Information We Collect about Your Usage</h3>",
      '<p>We may also automatically collect certain information about your interaction with the Services ("Usage Data"). To do this, we may use cookies, pixels and similar technologies ("Cookies"). Usage Data may include information about how you access and use our Site and your account, including device information, browser information, information about your network connection, your IP address and other information regarding your interaction with the Services.</p>',
      "<h3>Information We Obtain from Third Parties</h3>",
      "<ul>",
      "<li>Companies who support our Site and Services.</li>",
      "<li>Our payment processors, who collect payment information (e.g., bank account, credit or debit card information, billing address) to process your payment in order to fulfill your orders and provide you with products or services you have requested, in order to perform our contract with you.</li>",
      "<li>When you visit our Site, open or click on emails we send you, or interact with our Services or advertisements, we, or third parties we work with, may automatically collect certain information using online tracking technologies.</li>",
      "</ul>",
      "<p>Any information we obtain from third parties will be treated in accordance with this Privacy Policy.</p>",
      "<h3>How We Use Your Personal Information</h3>",
      "<ul>",
      "<li><strong>Providing Products and Services.</strong> We use your personal information to provide you with the Services in order to perform our contract with you, including to process your payments, fulfill your orders, send notifications related to your account, purchases, returns, exchanges or other transactions, create and manage your account, arrange for shipping, and facilitate returns and exchanges.</li>",
      "<li><strong>Marketing and Advertising.</strong> We may use your personal information for marketing and promotional purposes, such as to send marketing, advertising and promotional communications by email, text message or postal mail, and to show you advertisements for products or services.</li>",
      "<li><strong>Security and Fraud Prevention.</strong> We use your personal information to detect, investigate or take action regarding possible fraudulent, illegal or malicious activity. If you register an account, you are responsible for keeping your credentials safe. If you believe your account has been compromised, please contact us immediately.</li>",
      "<li><strong>Communicating with You and Service Improvement.</strong> We use your personal information to provide you with customer support and improve our Services.</li>",
      "</ul>",
      "<h3>Cookies</h3>",
      "<p>Like many websites, we use Cookies on our Site. We use Cookies to power and improve our Site and our Services (including to remember your actions and preferences), to run analytics and better understand user interaction with the Services. We may also permit third parties and service providers to use Cookies on our Site.</p>",
      "<p>Most browsers automatically accept Cookies by default, but you can choose to set your browser to remove or reject Cookies through your browser controls. Removing or blocking Cookies can negatively impact your user experience and may cause some of the Services to work incorrectly or no longer be available.</p>",
      "<h3>How We Disclose Personal Information</h3>",
      "<ul>",
      "<li>With vendors or other third parties who perform services on our behalf (e.g., IT management, payment processing, data analytics, customer support, cloud storage, fulfillment and shipping).</li>",
      "<li>With business and marketing partners to provide services and advertise to you. Our partners will use your information in accordance with their own privacy notices.</li>",
      "<li>When you direct, request us or otherwise consent to our disclosure of certain information to third parties.</li>",
      "<li>With our affiliates or otherwise within our corporate group.</li>",
      "<li>In connection with a business transaction such as a merger or bankruptcy, to comply with any applicable legal obligations, to enforce any applicable terms of service, and to protect or defend the Services, our rights, and the rights of our users or others.</li>",
      "</ul>",
      "<p>We do not use or disclose sensitive personal information without your consent or for the purposes of inferring characteristics about you.</p>",
      "<h3>Third Party Websites and Links</h3>",
      "<p>Our Site may provide links to websites or other online platforms operated by third parties. If you follow links to sites not affiliated or controlled by us, you should review their privacy and security policies and other terms and conditions. We do not guarantee and are not responsible for the privacy or security of such sites.</p>",
      "<h3>Children&rsquo;s Data</h3>",
      "<p>The Services are not intended to be used by children, and we do not knowingly collect any personal information about children. If you are the parent or guardian of a child who has provided us with their personal information, you may contact us using the contact details set out below to request that it be deleted.</p>",
      '<p>As of the Effective Date of this Privacy Policy, we do not have actual knowledge that we "share" or "sell" (as those terms are defined in applicable law) personal information of individuals under 16 years of age.</p>',
      "<h3>Security and Retention of Your Information</h3>",
      '<p>Please be aware that no security measures are perfect or impenetrable, and we cannot guarantee "perfect security". In addition, any information you send to us may not be secure while in transit. We recommend that you do not use insecure channels to communicate sensitive or confidential information to us.</p>',
      "<p>How long we retain your personal information depends on different factors, such as whether we need the information to maintain your account, to provide the Services, comply with legal obligations, resolve disputes or enforce other applicable contracts and policies.</p>",
      "<h3>Your Rights</h3>",
      "<ul>",
      "<li><strong>Right to Access / Know:</strong> You may have a right to request access to personal information that we hold about you.</li>",
      "<li><strong>Right to Delete:</strong> You may have a right to request that we delete personal information we maintain about you.</li>",
      "<li><strong>Right to Correct:</strong> You may have a right to request that we correct inaccurate personal information we maintain about you.</li>",
      "<li><strong>Right of Portability:</strong> You may have a right to receive a copy of the personal information we hold about you and to request that we transfer it to a third party.</li>",
      "<li><strong>Restriction of Processing:</strong> You may have the right to ask us to stop or restrict our processing of personal information.</li>",
      "<li><strong>Withdrawal of Consent:</strong> Where we rely on consent to process your personal information, you may have the right to withdraw this consent.</li>",
      "<li><strong>Appeal:</strong> You may have a right to appeal our decision if we decline to process your request.</li>",
      "<li><strong>Managing Communication Preferences:</strong> You may opt out of promotional emails at any time by using the unsubscribe option displayed in our emails to you.</li>",
      "</ul>",
      "<p>We will not discriminate against you for exercising any of these rights. We may need to collect information from you to verify your identity before providing a substantive response to the request.</p>",
      "<h3>Complaints</h3>",
      "<p>If you have complaints about how we process your personal information, please contact us using the contact details provided below. If you are not satisfied with our response, depending on where you live you may have the right to appeal our decision, or lodge your complaint with your local data protection authority.</p>",
      "<h3>International Users</h3>",
      "<p>Please note that we may transfer, store and process your personal information outside the country you live in. Your personal information is also processed by staff and third party service providers and partners in these countries.</p>",
      "<h3>Contact</h3>",
      '<p>Should you have any questions about our privacy practices or this Privacy Policy, or if you would like to exercise any of the rights available to you, please call or email us at <a href="mailto:support@hueglam.com">Support@hueglam.com</a>.</p>',
    ],
  },
  {
    slug: "terms-of-service",
    title: "Terms of service",
    updated: "2026-09-28",
    needsReview: true,
    body: [
      "<h3>Overview</h3>",
      "<p>This website is operated by H U E G L A M. Throughout the site, the terms &ldquo;we&rdquo;, &ldquo;us&rdquo; and &ldquo;our&rdquo; refer to H U E G L A M. H U E G L A M offers this website, including all information, tools and Services available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here.</p>",
      "<p>By visiting our site and/or purchasing something from us, you engage in our &ldquo;Service&rdquo; and agree to be bound by the following terms and conditions (&ldquo;Terms of Service&rdquo;, &ldquo;Terms&rdquo;), including those additional terms and conditions and policies referenced herein and/or available by hyperlink. These Terms of Service apply to all users of the site.</p>",
      "<p>Please read these Terms of Service carefully before accessing or using our website. By accessing or using any part of the site, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions of this agreement, then you may not access the website or use any Services.</p>",
      "<p>Any new features or tools which are added to the current store shall also be subject to the Terms of Service. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to our website. It is your responsibility to check this page periodically for changes.</p>",
      "<h3>Section 1 &ndash; Online Store Terms</h3>",
      "<p>By agreeing to these Terms of Service, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority and you have given us your consent to allow any of your minor dependents to use this site.</p>",
      "<p>You may not use our products for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction. You must not transmit any worms or viruses or any code of a destructive nature. A breach or violation of any of the Terms will result in an immediate termination of your Services.</p>",
      "<h3>Section 2 &ndash; General Conditions</h3>",
      "<p>We reserve the right to refuse Service to anyone for any reason at any time. You understand that your content (not including credit card information) may be transferred unencrypted and involve transmissions over various networks. Credit card information is always encrypted during transfer over networks.</p>",
      "<p>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service without express written permission by us.</p>",
      "<h3>Section 3 &ndash; Accuracy, Completeness and Timeliness of Information</h3>",
      "<p>We are not responsible if information made available on this site is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon as the sole basis for making decisions. Any reliance on the material on this site is at your own risk.</p>",
      "<h3>Section 4 &ndash; Modifications to the Service and Prices</h3>",
      "<p>Prices for our products are subject to change without notice. We reserve the right at any time to modify or discontinue the Service without notice. We shall not be liable to you or to any third party for any modification, price change, suspension or discontinuance of the Service.</p>",
      "<h3>Section 5 &ndash; Products or Services</h3>",
      '<p>Certain products or Services may be available exclusively online through the website. These products or Services may have limited quantities and are subject to return or exchange only according to our <a href="/pages/refund-policy">Refund Policy</a>.</p>',
      "<p>We have made every effort to display as accurately as possible the colors and images of our products. We cannot guarantee that your monitor&rsquo;s display of any color will be accurate. We reserve the right to limit the quantities of any products or Services that we offer, and to discontinue any product at any time.</p>",
      "<h3>Section 6 &ndash; Accuracy of Billing and Account Information</h3>",
      "<p>We reserve the right to refuse any order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. In the event that we make a change to or cancel an order, we may attempt to notify you by contacting the e-mail and/or billing address/phone number provided at the time the order was made.</p>",
      '<p>You agree to provide current, complete and accurate purchase and account information for all purchases made at our store. For more details, please review our <a href="/pages/refund-policy">Refund Policy</a>.</p>',
      "<h3>Section 7 &ndash; Optional Tools</h3>",
      "<p>We may provide you with access to third-party tools over which we neither monitor nor have any control nor input. You acknowledge and agree that we provide access to such tools &rdquo;as is&rdquo; and &ldquo;as available&rdquo; without any warranties. Any use by you of optional tools offered through the site is entirely at your own risk and discretion.</p>",
      "<h3>Section 8 &ndash; Third-Party Links</h3>",
      "<p>Certain content, products and Services available via our Service may include materials from third parties. We are not responsible for examining or evaluating the content or accuracy and we do not warrant and will not have any liability for any third-party materials or websites.</p>",
      "<h3>Section 9 &ndash; User Comments, Feedback and Other Submissions</h3>",
      "<p>If you send creative ideas, suggestions, proposals, plans, or other materials, you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us.</p>",
      "<p>You agree that your comments will not violate any right of any third party, and will not contain libelous or otherwise unlawful, abusive or obscene material. You are solely responsible for any comments you make and their accuracy.</p>",
      "<h3>Section 10 &ndash; Personal Information</h3>",
      '<p>Your submission of personal information through the store is governed by our <a href="/pages/privacy-policy">Privacy Policy</a>.</p>',
      "<h3>Section 11 &ndash; Errors, Inaccuracies and Omissions</h3>",
      "<p>Occasionally there may be information on our site that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, shipping charges, transit times and availability. We reserve the right to correct any errors and to change or update information or cancel orders if any information is inaccurate at any time without prior notice.</p>",
      "<h3>Section 12 &ndash; Prohibited Uses</h3>",
      "<p>You are prohibited from using the site or its content: for any unlawful purpose; to solicit others to perform or participate in any unlawful acts; to violate any regulations, rules or laws; to infringe upon our intellectual property rights or those of others; to harass, abuse, insult, harm, defame or discriminate; to submit false or misleading information; to upload or transmit viruses or malicious code; to collect or track the personal information of others; to spam, phish, pharm, pretext, spider, crawl, or scrape; for any obscene or immoral purpose; or to interfere with or circumvent the security features of the Service.</p>",
      "<h3>Section 13 &ndash; Disclaimer of Warranties; Limitation of Liability</h3>",
      "<p>We do not guarantee, represent or warrant that your use of our Service will be uninterrupted, timely, secure or error-free. You expressly agree that your use of, or inability to use, the Service is at your sole risk. The Service and all products delivered to you through the Service are (except as expressly stated by us) provided &lsquo;as is&rsquo; and &lsquo;as available&rsquo; for your use, without any representation, warranties or conditions of any kind.</p>",
      "<p>In no case shall H U E G L A M, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, Service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind.</p>",
      "<h3>Section 14 &ndash; Indemnification</h3>",
      "<p>You agree to indemnify, defend and hold harmless H U E G L A M and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, Service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys&rsquo; fees, made by any third party due to or arising out of your breach of these Terms of Service or your violation of any law or the rights of a third party.</p>",
      "<h3>Section 15 &ndash; Severability</h3>",
      "<p>In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed severed from these Terms of Service.</p>",
      "<h3>Section 16 &ndash; Termination</h3>",
      "<p>The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes. These Terms of Service are effective unless and until terminated by either you or us.</p>",
      "<h3>Section 17 &ndash; Entire Agreement</h3>",
      "<p>These Terms of Service and any policies or operating rules posted by us on this site constitute the entire agreement and understanding between you and us and govern your use of the Service. Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party.</p>",
      "<h3>Section 18 &ndash; Governing Law</h3>",
      "<p>These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of India.</p>",
      "<h3>Section 19 &ndash; Changes to Terms of Service</h3>",
      "<p>You can review the most current version of the Terms of Service at any time at this page. We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website.</p>",
      "<h3>Section 20 &ndash; Contact Information</h3>",
      '<p>Questions about the Terms of Service should be sent to us at <a href="mailto:support@hueglam.com">Support@hueglam.com</a>.</p>',
      "<p>Nyoraa Consumers Pvt Ltd<br>Plot B/5, Flat 201, MSR Complex, Adithya Nagar, Hyderabad 500085<br>Support@hueglam.com<br>8886677330</p>",
    ],
  },
];

export function getStaticPage(slug: string): StaticPage | null {
  return staticPages.find((p) => p.slug === slug) ?? null;
}
